index:
    path: /
    controller: App\Controller\DefaultController::index

app_login:
    path: /login
    controller: App\Controller\LoginController::index

registration:
    path: /registration
    controller: App\Controller\RegistrationController::index

success:
    path: /success
    controller: App\Controller\SuccessController::index

logout:
    path: /logout
