index:
    path: /
    controller: App\Controller\DefaultController::index

app_login:
    path: /login
    controller: App\Controller\LoginController::index

registration:
    path: /registration
    controller: App\Controller\RegistrationController::index

success:
    path: /success
    controller: App\Controller\SuccessController::index

admin:
    path: /admin
    controller: App\Controller\AdminController::index

Blog:
    path: /blog
    controller: App\Controller\BlogController::index

Newsletter:
    path: /newsletter
    controller: App\Controller\NewsletterController::index

updateManifest:
    path: /updatemanifest
    controller: App\Controller\SuccessController::updateManifest

entradastep2:    
    path: /blog/{id}
    controller: App\Controller\BlogController::entradasegonpas
    methods: [POST,GET]
    requirements:
        id: '[0-9]+'  

logout:
    path: /logout


